// Generated by CoffeeScript 2.7.0
var Actor;

import Vector2 from './vector2.js';

Actor = class Actor {
  constructor(x, y) {
    // constants
    this.max_acceleration = 10;
    this.max_speed = 120;
    this.position = new Vector2(0, 0);
    this.acceleration = new Vector2(0, 0);
    this.velocity = new Vector2(0, 0);
    this.forward = new Vector2(0, 0);
  }

  applyForce(force) {
    this.acceleration.add(force);
  }

  update() {}

  physics() {
    var delta_time;
    delta_time = 1 / 60;
    if (this.acceleration.magnitude() > this.max_acceleration) {
      this.acceleration.normalize().multiply(this.max_acceleration);
    }
    // integration step
    this.velocity.add(this.acceleration);
    if (this.velocity.magnitude() > this.max_speed) {
      this.velocity.normalize().multiply(this.max_speed);
    }
    this.position.add(Vector2.multiply(this.velocity, delta_time));
    this.forward = this.velocity.copy().normalize();
    this.acceleration = new Vector2(0, 0);
  }

};

export default Actor;
