// Generated by CoffeeScript 2.7.0
// get canvas
var canvas, context, raf, resizeCanvas, start;

canvas = document.getElementById('canvas');

context = canvas.getContext('2d');

resizeCanvas = function() {
  canvas.width = window.innerWidth;
  canvas.height = window.innerHeight;
};

window.addEventListener('orientationchange', resizeCanvas, false);

window.addEventListener('resize', resizeCanvas, false);

raf = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
  return window.setTimeout(callback, 1000 / 60);
};

import Boid from './boid.js';

start = function() {
  var draw, i, j, x, y;
// initialize boids
  for (i = j = 0; j < 500; i = ++j) {
    x = Math.random() * canvas.width;
    y = Math.random() * canvas.height;
    new Boid(x, y);
  }
  draw = function() {
    var boid, k, len, ref;
    context.clearRect(0, 0, canvas.width, canvas.height);
    ref = Boid.all;
    for (k = 0, len = ref.length; k < len; k++) {
      boid = ref[k];
      boid.update();
      boid.render(context);
    }
    return raf(draw);
  };
  draw();
};

// click event listener
canvas.addEventListener('click', function(event) {
  return new Boid(event.pageX, event.pageY);
});

// start immediately
setTimeout(function() {
  resizeCanvas();
  return start();
}, 0);
