// Generated by CoffeeScript 2.7.0
export var shared = {
  separationDistance: 24,
  separationForce: 4.75,
  alignmentForce: 2.90,
  cohesionForce: 4.25,
  boidCount: 500,
  boidRadius: 32,
  drawRadius: true,
  drawNeighbors: true
};
