// Generated by CoffeeScript 2.7.0
export var shared = {
  boidCount: 500,
  drawRadius: true,
  drawNeighbors: true,
  boidUseSeparationForce: false,
  boidUseAlignmentForce: false,
  boidUseCohesionForce: false,
  boidAlignmentWeight: 1.0,
  boidSeparationWeight: 2.5,
  boidCohesionWeight: 0.5,
  boidAvoidanceDist: 32,
  boidMaxSteerForce: 3.0,
  boidViewRadius: 64
};
